### ISSUE TITLE
Vasking av input i oppfølgingsplanen

### ISSUE THREAD

**Issue by JMLindseth** [navikt/oppfolgingsplanarbeidsgiver#53]
![image](https://user-images.githubusercontent.com/40055758/71264340-2bee3080-2344-11ea-9de2-50a31a271140.png)

Hvis man prøver å lage en tittel på arbeidsoppgave eller tiltak, som begynner med "mindre enn" og deretter tekst, vil ikke redux form gi beskjed om at det er ugyldig tekst, og lagring av opgpave/tiltak vil feile i backend. Dette fører til at brukeren får feilmelding med beskjed om å prøve igjen senere. Det er upraktisk, og burde fanges opp enten i det brukeren prøver å lagre, eller før vi prøver å skrive til database.

**Comment by Vitenok** [comment]
Issuen er fikset i disse commitene:
- https://github.com/navikt/oppfolgingsplanarbeidsgiver/commit/49a7a67aaa2e162357fa38ce91861cc649c35bbb
- https://github.com/navikt/oppfolgingsplan/commit/550b9fc96d6c5c2e8e705b8aae3f4785f3f64f03
